version: "3.9"
services:
  nginx:
    container_name: nginx-local
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
