
CREATE SCHEMA "gotecq--user";

CREATE TABLE "gotecq--user".user (
    _created timestamp without time zone,
    _creator uuid,
    _deleted timestamp without time zone,
    _etag character varying(1024),
    _id uuid PRIMARY KEY,
    _txt tsvector,
    _updated timestamp without time zone,
    _updater uuid,
    active boolean,
    address__city character varying(1024),
    address__country character varying(1024),
    address__line1 character varying(1024),
    address__line2 character varying(1024),
    address__postal character varying(1024),
    address__state character varying(1024),
    picture_id uuid,
    birthdate timestamp without time zone,
    expiration_date timestamp without time zone,
    gender character varying(1024),
    language character varying(255)[],
    last_login timestamp without time zone,
    name__family character varying(1024),
    name__given character varying(1024),
    name__middle character varying(1024),
    name__prefix character varying(1024),
    name__suffix character varying(1024),
    realm character varying(1024),
    svc_access character varying(1024),
    svc_secret character varying(1024),
    tags character varying(255)[],
    telecom__email character varying(1024),
    telecom__fax character varying(1024),
    telecom__phone character varying(1024),
    tfa_method character varying(1024),
    tfa_token character varying(1024),
    two_factor_authentication boolean,
    upstream_user_id uuid,
    user_type character varying(1024),
    username character varying(1024),
    verified_email character varying(1024),
    verified_phone character varying(1024),
    access_tags character varying(1024)[]
);
